import { UserModel } from "./modules/user/user.model";
import { RoleModel } from "./modules/role/role.model";
import { PartnerModel } from "./modules/partner/partner.model";
import { ClientModel } from "./modules/client/client.model";
import { ServiceModel } from "./modules/service/service.model";
import { ServicePricingModel } from "./modules/service/pricing.model";
import { ServiceRevenueRuleModel } from "./modules/service/revenue-rule.model";
import { LeadModel } from "./modules/lead/lead.model";
import { CaseModel } from "./modules/case/case.model";
import { CaseTaskModel } from "./modules/case/task.model";
import { DocumentModel } from "./modules/case/document.model";
import { InvoiceModel } from "./modules/finance/invoice.model";
import { PaymentModel } from "./modules/finance/payment.model";
import { RevenueLedgerEntryModel } from "./modules/finance/revenue-ledger.model";
import { PartnerStatementModel } from "./modules/finance/statement.model";
import { PartnerPayoutModel } from "./modules/finance/payout.model";
import { AuditLogModel } from "./modules/platform/audit-log.model";

console.log("All schemas imported successfully:");
console.log("- UserModel:", UserModel.modelName);
console.log("- RoleModel:", RoleModel.modelName);
console.log("- PartnerModel:", PartnerModel.modelName);
console.log("- ClientModel:", ClientModel.modelName);
console.log("- ServiceModel:", ServiceModel.modelName);
console.log("- ServicePricingModel:", ServicePricingModel.modelName);
console.log("- ServiceRevenueRuleModel:", ServiceRevenueRuleModel.modelName);
console.log("- LeadModel:", LeadModel.modelName);
console.log("- CaseModel:", CaseModel.modelName);
console.log("- CaseTaskModel:", CaseTaskModel.modelName);
console.log("- DocumentModel:", DocumentModel.modelName);
console.log("- InvoiceModel:", InvoiceModel.modelName);
console.log("- PaymentModel:", PaymentModel.modelName);
console.log("- RevenueLedgerEntryModel:", RevenueLedgerEntryModel.modelName);
console.log("- PartnerStatementModel:", PartnerStatementModel.modelName);
console.log("- PartnerPayoutModel:", PartnerPayoutModel.modelName);
console.log("- AuditLogModel:", AuditLogModel.modelName);
console.log("Schema validation check PASSED.");
